# CI Workflow Template
# Copy this to .github/workflows/ci.yml in your service repo

name: CI

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'pom.xml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'app/**'
      - 'pom.xml'

env:
  # Use organization's builder image for consistent builds
  BUILDER_IMAGE: ghcr.io/yourorg/java-builder:24
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yourorg/java-builder:24
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: /home/builder/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run unit tests
        run: mvn -B verify -DskipITs
        working-directory: app

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/target/site/jacoco/
          retention-days: 7

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yourorg/java-builder:24
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: /home/builder/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile
        run: mvn -B compile -DskipTests
        working-directory: app

      - name: Checkstyle
        run: mvn -B checkstyle:check
        working-directory: app

      - name: SpotBugs
        run: mvn -B spotbugs:check
        working-directory: app

      - name: PMD
        run: mvn -B pmd:check
        working-directory: app

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-and-test]
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'maven'

      - name: Run integration tests
        run: ./mvnw -B verify -DskipUTs=true
        working-directory: app

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build-and-test, code-quality, integration-test]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
